### ISSUE TITLE
If listNetworks api call provides more than 1 network this function returns more than 1 network which is incorrect

### ISSUE THREAD

**Issue by mvangoor** [MissionCriticalCloud/vagrant-cosmic#12]
https://github.com/MissionCriticalCloud/vagrant-cosmic/blob/a256286a056d7ab977fea08b7c6b96cc1990ae60/lib/vagrant-cosmic/action/run_instance.rb#L477

**Comment by shoekstra** [comment]
Hey @mvangoor,

If I read this correctly, when you have two or more VPC tiers with the same name you receive an error, is that right? Also could you please attach the full stacktrace when the issue is encountered.

Thanks!

**Comment by mvangoor** [comment]
Hi @shoekstra ,

I do not think the name similarity has anything to do with it.

Stack trace:

```
 /root/.vagrant.d/gems/2.4.9/gems/vagrant-cosmic-0.2.0/lib/vagrant-cosmic/action/run_instance.rb:464:in `compose_port_forwarding_rule_creation_options': undefined method `id' for nil:NilClass (NoMethodError)
        	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-cosmic-0.2.0/lib/vagrant-cosmic/action/run_instance.rb:421:in `apply_port_forwarding_rule'
        	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-cosmic-0.2.0/lib/vagrant-cosmic/action/run_instance.rb:382:in `block in create_randomport_forwarding_rule'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/util/retryable.rb:17:in `retryable'
        	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-cosmic-0.2.0/lib/vagrant-cosmic/action/run_instance.rb:377:in `create_randomport_forwarding_rule'
        	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-cosmic-0.2.0/lib/vagrant-cosmic/action/run_instance.rb:366:in `block in generate_and_apply_port_forwarding_rules_for_communicators'
        	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-cosmic-0.2.0/lib/vagrant-cosmic/action/run_instance.rb:351:in `each'
        	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-cosmic-0.2.0/lib/vagrant-cosmic/action/run_instance.rb:351:in `generate_and_apply_port_forwarding_rules_for_communicators'
        	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-cosmic-0.2.0/lib/vagrant-cosmic/action/run_instance.rb:316:in `configure_port_forwarding'
        	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-cosmic-0.2.0/lib/vagrant-cosmic/action/run_instance.rb:253:in `configure_networking'
        	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-cosmic-0.2.0/lib/vagrant-cosmic/action/run_instance.rb:41:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-cosmic-0.2.0/lib/vagrant-cosmic/action/warn_networks.rb:14:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/provision.rb:80:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:130:in `block in finalize_action'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builder.rb:116:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `block in run'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/util/busy.rb:19:in `busy'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `run'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/call.rb:53:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-cosmic-0.2.0/lib/vagrant-cosmic/action/connect_cosmic.rb:42:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builder.rb:116:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `block in run'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/util/busy.rb:19:in `busy'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `run'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/machine.rb:238:in `action_raw'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/machine.rb:209:in `block in action'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:613:in `lock'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/machine.rb:195:in `call'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/machine.rb:195:in `action'
        	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

The function has 0 guards to only respond 1 entry, which is however what it is expected from the place it is being called.
